# pylint: disable=C0103
# Generated by Django 4.2.19 on 2025-03-02 13:09

import django.db.models.deletion
import ovinc_client.core.models
import ovinc_client.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "prompt_price",
                    models.DecimalField(
                        decimal_places=12,
                        default=60,
                        help_text="Prompt price for 1m tokens",
                        max_digits=24,
                        verbose_name="Prompt Price",
                    ),
                ),
                (
                    "completion_price",
                    models.DecimalField(
                        decimal_places=12,
                        default=60,
                        help_text="Completion price for 1m tokens",
                        max_digits=24,
                        verbose_name="Completion Price",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Model ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Model",
                "ordering": ["model_id"],
            },
        ),
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="User Name"),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Email"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=12,
                        default=0,
                        max_digits=24,
                        verbose_name="Balance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "prompt_price",
                    models.DecimalField(
                        decimal_places=12,
                        default=60,
                        help_text="Prompt price for 1m tokens",
                        max_digits=24,
                        verbose_name="Prompt Price",
                    ),
                ),
                (
                    "completion_price",
                    models.DecimalField(
                        decimal_places=12,
                        default=60,
                        help_text="Completion price for 1m tokens",
                        max_digits=24,
                        verbose_name="Completion Price",
                    ),
                ),
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(db_index=True, max_length=255, verbose_name="User ID"),
                ),
                (
                    "chat_id",
                    models.CharField(db_index=True, max_length=255, verbose_name="Chat ID"),
                ),
                ("prompt_tokens", models.BigIntegerField(verbose_name="Prompt Tokens")),
                (
                    "completion_tokens",
                    models.BigIntegerField(verbose_name="Completion Tokens"),
                ),
                (
                    "user_info",
                    models.JSONField(blank=True, default=dict, null=True, verbose_name="User Info"),
                ),
                (
                    "usage",
                    models.JSONField(blank=True, default=dict, null=True, verbose_name="Usage"),
                ),
                (
                    "chat_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Chat at"),
                ),
                (
                    "model",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usage.aimodel",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Log",
                "verbose_name_plural": "Usage Log",
                "ordering": ["-chat_at"],
            },
        ),
    ]
