# pylint: disable=C0103
# Generated by Django 4.2.19 on 2025-03-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={
                "ordering": ["model_name"],
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Model",
            },
        ),
        migrations.AlterModelOptions(
            name="userbalance",
            options={
                "ordering": ["user_name"],
                "verbose_name": "User Balance",
                "verbose_name_plural": "User Balance",
            },
        ),
        migrations.AddField(
            model_name="aimodel",
            name="model_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Model Name",
            ),
        ),
        migrations.AlterField(
            model_name="userbalance",
            name="user_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="User Name",
            ),
        ),
    ]
