# pylint: disable=C0103,C0415
# Generated by Django 4.2.19 on 2025-03-03 07:26

import django.db.models.deletion
import ovinc_client.core.models
from django.db import migrations


def clear_data(*args, **kwargs):
    from apps.usage.models import UsageLog

    UsageLog.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("usage", "0002_alter_aimodel_options_alter_userbalance_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usagelog",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="usagelog",
            name="user_info",
        ),
        migrations.AddField(
            model_name="usagelog",
            name="user",
            field=ovinc_client.core.models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="usage.userbalance",
                verbose_name="User",
            ),
        ),
        migrations.RunPython(clear_data),
    ]
